import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import { getKeys } from "../utils";
import NodeRSA from "node-rsa";
import axios from "axios";

export default function Home() {
  const [userMessage, setUserMessage] = useState("");
  const [ownPrivateKey, setOwnPrivateKey] = useState(null);
  const [ownPublicKey, setOwnPublicKey] = useState(null);
  const [serverPublicKey, setServerPublicKey] = useState(null);
  const [serverMsg, setServerMsg] = useState(null);
  async function handlerButton() {
    const serverKey = new NodeRSA();
    console.log(serverPublicKey);
    await serverKey.importKey(serverPublicKey, "public");
    console.log(userMessage);
    const encriptedMessage = await serverKey.encrypt(userMessage, "base64");
    console.log(
      "mensagem encriptada com chave pública",
      encriptedMessage
    );
    const res = await axios.post("http://localhost:8080/", {
      msg: encriptedMessage
    });
    const decrypter = await new NodeRSA(ownPrivateKey);
    const decriptedMessage = await decrypter.decrypt(res.data.msg);
    setServerMsg(decriptedMessage.toString());
    /* await key.importKey(ownPrivateKey, "private");
    console.log("mensagem descriptografada com chave privada",  key.decrypt(encriptedMessage).toString()); */
  }
  useEffect(() => {
    const generateKeys = async () => {
      const keys = await getKeys();
      setOwnPrivateKey(keys[0]);
      setOwnPublicKey(keys[1]);
     const req = await axios.post("http://localhost:8080/keys", {
        publicKey: keys[1],
      });
      const receivedPublicKey  = req.data.serverPublicKey;
      await setServerPublicKey(receivedPublicKey);
    };
    generateKeys();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <h1>
          Digite a mensagem para ser enviada de forma segura para o servidor:{" "}
        </h1>
        <input
          type="text"
          id="mensagem"
          value={userMessage}
          onChange={(e) => setUserMessage(e.target.value)}
        />
        <button onClick={handlerButton}>
          Clique aqui para enviar a mensagem
        </button>

        {serverMsg !== null && <h1>Mensagem do servidor: {serverMsg}</h1>}
      </section>
    </div>
  );
}
