import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [userMessage, setUserMessage] = useState("");
  function handlerButton() {}

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <h1>
          Digite a mensagem para ser enviade de forma segura para o servidor:{" "}
        </h1>
        <input
          type="text"
          id="mensagem"
          value={userMessage}
          onChange={(e) => setUserMessage(e.target.value)}
        />
        <button onClick={handlerButton}>Clique aqui para enviar a mensagem</button>
      </section>
    </div>
  );
}
